apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Dialogmøtekandidat-status for sykmeldte personer"
    dcat.data.nav.no/description: >-
      Topic inneholder informasjon om sykmeldte personer er kandidat for dialogmøte.
  name: isdialogmotekandidat-dialogmotekandidat
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: {{ kafkaPool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykefravr
      application: isdialogmotekandidat
      access: readwrite
    - team: teamsykefravr
      application: syfooversiktsrv
      access: read
