apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Dialogmøtekandidat-status for sykmeldte personer. Topic er kun midlertidig for bruk av Syfomotebehov"
    dcat.data.nav.no/description: >-
      Topic inneholder informasjon om sykmeldte personer er kandidat for dialogmøte. Topic er kun midlertidig til bruk av av Syfomotebehov, kan slettes etter overgang til topic "isdialogmotekandidat-dialogmotekandidat" i prod.
  name: isdialogmotekandidat-dialogmotekandidat-midlertidig
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: {{ kafkaPool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykefravr
      application: isdialogmotekandidat
      access: readwrite
    - team: teamsykefravr
      application: syfomotebehov
      access: read
