apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmotekandidat
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isdialogmotekandidat.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: isoppfolgingstilfelle
        - application: syfo-tilgangskontroll
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: isdialogmotekandidat-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "http://syfo-tilgangskontroll"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: "http://isoppfolgingstilfelle"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: STOPPUNKT_CRONJOB_DELAY
      value: "240"
    - name: OUTDATED_DIALOGMOTEKANDIDAT_CUTOFF
      value: "2023-06-01"
    - name: OUTDATED_DIALOGMOTEKANDIDAT_CRONJOB_ENABLED
      value: "false"
