ALTER TABLE DIALOGMOTESTATUS RENAME COLUMN ferdigstilt_tidspunkt TO status_tidspunkt;
ALTER TABLE DIALOGMOTESTATUS ADD COLUMN status_type VARCHAR(50) NOT NULL DEFAULT 'FERDIGSTILT';
ALTER TABLE DIALOGMOTESTATUS ALTER COLUMN status_type DROP DEFAULT;
