CREATE TABLE MIDLERTIDIG_DIALOGMOTEKANDIDAT_ENDRING
(
    id          SERIAL PRIMARY KEY,
    uuid        CHAR(36)    NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL,
    personident VARCHAR(11) NOT NULL,
    kandidat    BOOLEAN     NOT NULL,
    arsak       VARCHAR(30) NOT NULL
);

CREATE INDEX IX_TEMP_DIALOGMOTEKANDIDAT_ENDRING_PERSONIDENT on MIDLERTIDIG_DIALOGMOTEKANDIDAT_ENDRING (personident);
