name: kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/kafka-dialogmotekandidat.yaml'
      - '.nais/kafka/dialogmotekandidat.yaml'
      - '.nais/kafka/dev.json'
      - '.nais/kafka/prod.json'

permissions:
  id-token: write

jobs:
  deploy-kafka-dialogmotekandidat-dev:
    name: Deploy Kafka topic Dialogmotekandidat to NAIS dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/dialogmotekandidat.yaml
          VARS: .nais/kafka/dev.json

  deploy-kafka-dialogmotekandidat-prod:
    name: Deploy Kafka topic Dialogmotekandidat to NAIS prod-gcp
    needs: deploy-kafka-dialogmotekandidat-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/dialogmotekandidat.yaml
          VARS: .nais/kafka/prod.json

